### ISSUE TITLE
When will an official release and nuget package be available?

### ISSUE THREAD

**Issue by mdabros** [interesaaat/TorchSharp#19]
Hi @interesaaat,

Thanks for the big effort to bring training to TorchSharp. Do you have a rough estimate of when all your efforts will be merged to `xamarin/TorchSharp`, and release on nuget?

Best regards
Mads

**Comment by interesaaat** [comment]
Hi! We are working on integrating (libTorchSharp)[https://github.com/interesaaat/LibTorchSharp] with TorchSharp, and automate the build process. After that we should be ready to go.

@artidoro

**Comment by mdabros** [comment]
Thanks for the update. Looking forward to the merge/release 👍

**Comment by joemoorhouse** [comment]
Also looking forward to the release! Have a (actually non-ML) application I think this is perfect for.

**Comment by interesaaat** [comment]
@mdabros @joemoorhouse we merged back this code into [xamarin\TorchSharp](https://github.com/xamarin/TorchSharp). We have an [issue](https://github.com/xamarin/TorchSharp/issues/10) tracking the publication of the nuget.
